<?php

namespace Faker\Provider\dv_MV;

class Company extends \Faker\Provider\en_US\Company
{
  protected static $catchPhraseWords = array(
      array(
          'Adaptive', 'Advanced', 'Ameliorated', 'Assimilated', 'Automated', 'Balanced', 'Business-focused', 'Centralized', 'Cloned', 'Compatible', 'Configurable', 'Cross-group', 'Cross-platform', 'Customer-focused', 'Customizable', 'Decentralized', 'De-engineered', 'Devolved', 'Digitized', 'Distributed', 'Diverse', 'Down-sized', 'Enhanced', 'Enterprise-wide', 'Ergonomic', 'Exclusive', 'Expanded', 'Extended', 'Facetoface', 'Focused', 'Front-line', 'Fully-configurable', 'Function-based', 'Fundamental', 'Future-proofed', 'Grass-roots', 'Horizontal', 'Implemented', 'Innovative', 'Integrated', 'Intuitive', 'Inverse', 'Managed', 'Mandatory', 'Monitored', 'Multi-channelled', 'Multi-lateral', 'Multi-layered', 'Multi-tiered', 'Networked', 'Object-based', 'Open-architected', 'Open-source', 'Operative', 'Optimized', 'Optional', 'Organic', 'Organized', 'Persevering', 'Persistent', 'Phased', 'Polarised', 'Pre-emptive', 'Proactive', 'Profit-focused', 'Profound', 'Programmable', 'Progressive', 'Public-key', 'Quality-focused', 'Reactive', 'Realigned', 'Re-contextualized', 'Re-engineered', 'Reduced', 'Reverse-engineered', 'Right-sized', 'Robust', 'Seamless', 'Secured', 'Self-enabling', 'Sharable', 'Stand-alone', 'Streamlined', 'Switchable', 'Synchronised', 'Synergistic', 'Synergized', 'Team-oriented', 'Total', 'Triple-buffered', 'Universal', 'Up-sized', 'Upgradable', 'User-centric', 'User-friendly', 'Versatile', 'Virtual', 'Visionary', 'Vision-oriented'
      ),
      array(
          '24hour', '24/7', '3rdgeneration', '4thgeneration', '5thgeneration', '6thgeneration', 'actuating', 'analyzing', 'assymetric', 'asynchronous', 'attitude-oriented', 'background', 'bandwidth-monitored', 'bi-directional', 'bifurcated', 'bottom-line', 'clear-thinking', 'client-driven', 'client-server', 'coherent', 'cohesive', 'composite', 'context-sensitive', 'contextually-based', 'content-based', 'dedicated', 'demand-driven', 'didactic', 'directional', 'discrete', 'disintermediate', 'dynamic', 'eco-centric', 'empowering', 'encompassing', 'even-keeled', 'executive', 'explicit', 'exuding', 'fault-tolerant', 'foreground', 'fresh-thinking', 'full-range', 'global', 'grid-enabled', 'heuristic', 'high-level', 'holistic', 'homogeneous', 'human-resource', 'hybrid', 'impactful', 'incremental', 'intangible', 'interactive', 'intermediate', 'leadingedge', 'local', 'logistical', 'maximized', 'methodical', 'mission-critical', 'mobile', 'modular', 'motivating', 'multimedia', 'multi-state', 'multi-tasking', 'national', 'needs-based', 'neutral', 'nextgeneration', 'non-volatile', 'object-oriented', 'optimal', 'optimizing', 'radical', 'real-time', 'reciprocal', 'regional', 'responsive', 'scalable', 'secondary', 'solution-oriented', 'stable', 'static', 'systematic', 'systemic', 'system-worthy', 'tangible', 'tertiary', 'transitional', 'uniform', 'upward-trending', 'user-facing', 'value-added', 'web-enabled', 'well-modulated', 'zeroadministration', 'zerodefect', 'zerotolerance'
      ),
      array(
          'ability', 'access', 'adapter', 'algorithm', 'alliance', 'analyzer', 'application', 'approach', 'architecture', 'archive', 'artificialintelligence', 'array', 'attitude', 'benchmark', 'budgetarymanagement', 'capability', 'capacity', 'challenge', 'circuit', 'collaboration', 'complexity', 'concept', 'conglomeration', 'contingency', 'core', 'customerloyalty', 'database', 'data-warehouse', 'definition', 'emulation', 'encoding', 'encryption', 'extranet', 'firmware', 'flexibility', 'focusgroup', 'forecast', 'frame', 'framework', 'function', 'functionalities', 'GraphicInterface', 'groupware', 'GraphicalUserInterface', 'hardware', 'help-desk', 'hierarchy', 'hub', 'implementation', 'info-mediaries', 'infrastructure', 'initiative', 'installation', 'instructionset', 'interface', 'internetsolution', 'intranet', 'knowledgeuser', 'knowledgebase', 'localareanetwork', 'leverage', 'matrices', 'matrix', 'methodology', 'middleware', 'migration', 'model', 'moderator', 'monitoring', 'moratorium', 'neural-net', 'openarchitecture', 'opensystem', 'orchestration', 'paradigm', 'parallelism', 'policy', 'portal', 'pricingstructure', 'processimprovement', 'product', 'productivity', 'project', 'projection', 'protocol', 'securedline', 'service-desk', 'software', 'solution', 'standardization', 'strategy', 'structure', 'success', 'superstructure', 'support', 'synergy', 'systemengine', 'task-force', 'throughput', 'time-frame', 'toolset', 'utilisation', 'website', 'workforce'
      )
  );
  protected static $bsWords = array(
      array(
          'އުފައްދާ', 'ބޭނުންކޮށް', 'ހިމަނައިގެން', 'ފަސޭހަކޮށް', 'ހަރަދުކުޑަ', 'ބަދަލުކޮށް', 'ތަފާތުކޮށް', 'ހިމަނައިގެން', 'ހޯދުމަށް', 'ދެއްކުމަށް', 'އަޅާކިޔާ', 'އީޖާދުކޮށް', 'ޖުމްލަކޮށް', 'އުފެއްދުމަށް', 'އިތުރުކުރުމަށް', 'ހިތްވަރުދީ', 'ބަދަލުގެނެސް', 'ހިތްވަރާއި', 'ދުރާލާ', 'ވިޔަފާރިކުރުމަށް', 'ބޭނުންކޮށްގެން', 'ވަސީލަތްކޮށް', 'ހޯދައި', 'ދޭތެރެހޯދާ', 'ކުރިއަރުވާ', 'އުކުޅުތަށް ހޯދައި', 'ހުޅުވައިދީ', 'ބްެރޭންޑް', 'ބޮޑުކޮށް', 'އަމާޒް', 'މެދުވެރިކޮށް', 'އުުފައްދައި', 'ފޯރުކޮށްދީ', 'ދަލު', 'އެތެރެއިން', 'ބޭނުންކޮށްގެން', 'ކުރިއަރުވައި', 'އަޅާކިޔާ', 'ކުރިއަރުވައިގެން', 'މެދުތެރެއިން', 'ވައިޓްބޯޑް', 'ހިޔާލުކޮށް', 'އާބޭނުންތަކަށް', 'ވިސްނާ', 'ބޮޑުމަންޒަރު', 'ދޫކޮށްލާ', 'ދުއްވައި', 'ދިގުކޮށް', 'އިންޖިނިއަރު', 'އެއްކޮށް ބަދަލުކޮށް', 'އުފައްދާ', 'ބޭނުންހޯދައި', 'ބަދަލުވުމުގެ މަގު', 'އާރާސްތުކޮށް', 'އެކިފަހަރުމަތިން', 'ގޮވާންކޮށް', 'މެޓްރިކްސް', 'އުފައްދަން ބޭނުންކޮށް', 'އަލުން ހޯދާ', 'އަލުން ބަޔާންކޮށް'
      ),
      array(
          'ފިއްތާ ސިމެންތި', 'އަގު އިތުރު', 'މައްޗަށް', 'ދުރާލާ ވިސްނާ', 'ހަރުދަނާ', 'މުޅިން އާގޮތަކަށް', 'ފަސޭހަކޮށް', 'އެންމެ ފަހުގެ', 'މޮޅު', 'ދެނެގަންނަ', 'މިސްރާބު ރަނގަޅު', 'އިލެކްޓްރޯނިކް ވިޔަފާރި', 'އަމާޒްތަކަށް ވިސްނާ', 'ފަސޭހައިން ހިނގާ', 'އެކާއި އެކެއް', '24/7', 'end-to-end', 'global', 'ބީ2ބީ', 'ބީ2ސީ', 'ކުދި ކުދި', 'ބުރަކިނެތި', 'މަސްނުވާ', 'އަވަހަށް އަށަގަންނަ', 'ބަދަލުވާ', '24/365', 'އެންމެ މޮޅު', 'މަރާލައި', 'އަޅައިގަންނަ', 'އެންމެ ފަހުގެ', 'ވެބްސައިޓަކުން ބަލާލެވޭ', 'ބެލުންތެރިންނާއެކީ', 'ޑޮޓްކޮމް', 'ރީތި', 'ފަހަތުބައި', 'ވަގުތުން', 'ހަރަދުކުޑަ', 'ކުރީބައި', 'ބަހާފައި', 'އެކުއެކީގައި', 'އިތުރުކުރެވޭ', 'ޓާންކީ', 'ދުނިޔޭގެ ފެންވަރު', 'ސޯސް ހުޅުވިފައި', 'ހުރިހާ ސްޓޭޖެއްގައި', 'ހުރިހާ މީޑިއާއެއްގައި', 'އެތެރެއިން ބާރު ހޯދައި', 'ގަލާއި ކްލިކް', 'އެންމެ ފުރަތަމަވެސް', 'އެންޓަރޕްރައިސް', 'އެތެރެއިން', 'ބޭނުންތެރި', 'ވަޔަރނުލާ', 'ދެފުށްފެންނަ', 'ފަހުގެޖީލް', 'އެންމެ ފަހުގެ', 'ބޭނުންކުރާމީހާއަށް ފަސޭހަ', 'ދުރުވިސްނޭ', 'ބަދަލުކޮށްފައި', 'ކޮންމެމީހަކަށްވެސް', 'ގުޅާފައިކުޅެވޭ', 'އެކުއެކީގައި', 'ބޭނުންކުރާހިތްވާ', 'ހުރިހާކަމަކަށް ފުދޭ', 'މުއްސަނދި'
      ),
      array(
          'ގުޅިފައި', 'އިންޓަރނެޓަށް ތައްޔާރު', 'ހުރިހާ ގޮތަކަށް', 'މާކެޓްތަކަށް', 'ޕާޓްނަރޗިޕް', 'ވަސީލަތްތައް', 'ސްޓޭޖްތައް', 'ހިޔާލު', 'ފޯރުކޮށްދޭ ވަސީލަތްތައް', 'ލޮލުގެ', 'ގްރޫޕްތައް', 'ފައިދާ', 'ހައްލު', 'އިލެކްޓްރޯނިކް ފެހުން', 'އިލެކްޓްރީނިކް ހިދުމަތް', 'ކުރަންޖެހޭ ކަންތައް', 'ފިހާރަ', 'އާއްމުނޫން', 'އުފެއްދުންތައް', 'ބައިތައް', 'ވޯޓްކުރުމަށް', 'ސަޕްލައިކުރާ މީހުން', 'ހުރިހާކަމަކަށް', 'ގުޅުން', 'ފަރުމާ', 'ފަރުދާ', 'އިލެކްޓްރޯނިކް މާރކެޓް', 'އިލެކްޓްރޯނިކް ވިޔަފާރި', 'ސިިސްޓަމްތައް', 'ބޭނުންކުރެވޭވަރު', 'މައުލޫމާތުތައް', 'މޮޑެލް', 'ހިއްސާކޮށް', 'އުފެއްދުން', 'ބޭނުންތެރިން', 'ޑިޒައިން', 'ނެޓްވޯކް', 'އެޕްލިކޭޝަން', 'މެޓްރިކް މައުލޫމާތު', 'އިލެކްޓްރޯނިކް ވިޔަފާރިތައް', 'ކުރަންޖެހޭގޮތް', 'ތަޖުރިބާތައް', 'އިންޓަރނެޓް ހިދުމަތްތައް', 'ކުރާނެގޮތް'
      )
  );
  protected static $companySuffix = array('ލލސ', 'ޕވޓ ލޓޑ', 'ޕލސ', 'ގްރޫޕް', 'ލޓޑ', 'ޕާރޓްނާސް', 'އެސޯސިއޭޓްސް');

}
